### ISSUE TITLE
Definition of the Commission Tier

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#15]
I'm looking through the system and wondering where the Commission Tiers are defined.

I see where I select them and even where I can rename them. However, I'm not seeing where I define them ie. tell the system what percentage of commission or discount should be applied to sales through vendors of that level.

Thanks,
Karen

**Comment by brashrebel** [comment]
This isn't a feature we factored into our initial plan as there was no expressed need for it. However, I tend to believe it is necessary so we're going to put in the extra hour it will take to implement this.

**Comment by TDFvance** [comment]
Thanks. I appreciate it. I think it makes sense for this to be updateable as the company scales.

**Comment by TDFvance** [comment]
Where is this functionality located now?

**Comment by joelworsham** [comment]
In the plugin's settings page: "Settings -> MLM Settings"

**Comment by TDFvance** [comment]
So I take it the number after the colon is the discount/commission. Correct? And that’s where I’d change it if need be?

**Comment by joelworsham** [comment]
Correct.
