### ISSUE TITLE
Generic shop links do not work:

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#16]
These should be unassigned to any distributor if someone goes to one of these links to buy a product.

http://k5skinnutrition.com/shop/k5-total-body-formula-250-ml/
![k5error](https://cloud.githubusercontent.com/assets/12396651/7941387/f3a0438c-0924-11e5-9c50-8f066fae5726.JPG)

**Comment by joelworsham** [comment]
I don't understand the issue

**Comment by TDFvance** [comment]
You can't view any products when you link to them from:

www.k5skinnutrition.com/shop
So all product extensions for /shop/**\* links don't work.
There is no way to buy products UNLESS you have a distributor.

We don't want to pay commission to someone if they had nothing to do with acquiring the customer. So the generic shop should be able to sell products - not just the vendors.

**Comment by joelworsham** [comment]
`http://k5skinnutrition.com/shop/` is working for me. You're seeing that screenshot when you go that link?

**Comment by brashrebel** [comment]
@joelworsham I see and understand the issue. When visiting /shop it is not possible to simply select a product and purchase it without going through a vendor.

**Comment by TDFvance** [comment]
I found a work around.
