### ISSUE TITLE
COS clarification

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#18]
This line is appearing on the WooCommerce Report, Vendors tab. Is this calculating Cost of Sales (COS)? Or something else?

And if so, do I enter a COS on a per product basis? And if so where?
![cos](https://cloud.githubusercontent.com/assets/12396651/7942793/89b9600c-092e-11e5-8e74-39d09833da49.JPG)

**Comment by joelworsham** [comment]
Yes, cost of sales.

**Comment by TDFvance** [comment]
Where do I tell the system what the COS is for each product?

**Comment by joelworsham** [comment]
It was decided that the COS was a flat rate of $5 per product. So we did not program in the ability to change it.

**Comment by TDFvance** [comment]
It’s $5 per bottle. So unfortunately, we have a little problem there because some products have more than one bottle in them. (the combo pack has two bottles and the distributor pack has 6 bottles.)
