### ISSUE TITLE
Coupon code error

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#19]
It doesn't appear as though I can utilize a coupon in combination with the system. Can you take a look at this?

![couponcodeerror](https://cloud.githubusercontent.com/assets/12396651/7943167/e0bc14e2-0930-11e5-9879-d012a3fd5583.JPG)

**Comment by TDFvance** [comment]
If I log in as a customer or distributor, the coupons work just fine. So, for example, logged in as Allison Deming, I can get both my Distributor discount and my North America discount (body2015) to have the price correctly reflect what I'm purchasing.

The error seems to appear if I try to apply the coupon PRIOR TO signing in as a customer (as a first-time customer is likely to do.)

Thoughts?

**Comment by joelworsham** [comment]
This is definitely an issue with the plugin. We are currently looking into this.

**Comment by joelworsham** [comment]
Fixed in b2bbd07
