### ISSUE TITLE
Distributors unable to purchase "Private Products"

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#20]
I've messed with User Roles for "Vendors" and was finally able to get Distributor-only "Private" products to display in their store when they're logged in (I had to enable Edit Private Products and
Edit Others Products - which I don't want them to be able to actually do.) Instead, this should work by just enabling "Read Private Products". However, it is not. I believe this may be tied to the same issue that is preventing the generic store from working, because at one point I was redirected to the generic store and told Vendor not found.

Even when I get them to display using the "Edit" user role permission, I still can't seem to make it possible for them to put those products in the cart.

I believe there is some interference from the plugin because the labels are misaligned on the product page -- Under Vendor it's showing the Category and under Category its showing the tags, etc. Could this be part of the problem?
![misalignment](https://cloud.githubusercontent.com/assets/12396651/7948333/1ce8d232-0951-11e5-9098-b6049560708c.JPG)
![privateproducts](https://cloud.githubusercontent.com/assets/12396651/7948334/1cead154-0951-11e5-957a-d416cd6f0a7a.JPG)

![privateproducts](https://cloud.githubusercontent.com/assets/12396651/7948236/6a353ab8-0950-11e5-9336-6107aa0dd435.JPG)

**Comment by joelworsham** [comment]
The reason for this is that WooCommerce is built so that private products are not purchasable. We will need to figure out another solution, but I believe it will probably exist in a separate plugin.

**Comment by TDFvance** [comment]
What about using Groups? Will that interfere with your Plugin?

So, instead of marking them as Private. Can they be marked only for a specific group?
https://wordpress.org/plugins/groups/

**Comment by TDFvance** [comment]
So instead of making them private - I simply excluded the category from the shop page. That should prevent regular customers from seeing these items.

However, if a distributor buys from this page - http://k5skinnutrition.com/product-category/distributor-items/ - will it appear in their total sales?

There's a $399 (no commission) product among the distributor items. Credit for these purchases should be given toward volume goals and total team sales. If they don't have the "/shop/vendor-slug" sequence in the URL, will the distributor get credit here?

If this page can be included in the sales credit for the distributor (they would always be logged in when purchasing this from themselves), then we'll need to add this page to the Distributor menu in the upper left list so that they can find the product quickly and easily.

**Comment by joelworsham** [comment]
Because the link you sent me does not exist in a vendor store, it will not be credited towards anybody. Is this the desired result?

**Comment by TDFvance** [comment]
I found a work around
