### ISSUE TITLE
Vendor Report

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#22]
I have one item:
I need the reports to include a Customers by Vendor report somehow. This could appear in whichever of these three ways is best:
1) as a column in the Customer List (with each customer assigned to a Vendor)
2) with each Vendor name clickable to a list of their orders
3) As a Customers by Vendor button within the Vendors of tabs

Please advise if this is doable.

**Comment by brashrebel** [comment]
We'll discuss this tomorrow and let you know how much time it will take.

**Comment by TDFvance** [comment]
![Uploading ClickableVendors.JPG…]()
![customerlist](https://cloud.githubusercontent.com/assets/12396651/8291821/e6f9a314-18f9-11e5-85a4-6c98d1b94f74.JPG)

**Comment by TDFvance** [comment]
Can you describe the change you've made? Where will the customers by vendor be visible?

**Comment by TDFvance** [comment]
![error](https://cloud.githubusercontent.com/assets/12396651/8454935/e6d37f82-1fce-11e5-84f8-28e3bc09a457.JPG)

**Comment by TDFvance** [comment]
I clicked on the Vendor name in the report and receive this error.

**Comment by joelworsham** [comment]
Sorry, I have not yet uploaded the plugin to the server. I can do that now.

**Comment by joelworsham** [comment]
And I went with 2. So you can click on the vendor names in the report and it will take you to a curated list of their orders

**Comment by joelworsham** [comment]
It appears to be functioning properly now (though there are currently no vendor orders to view)

**Comment by TDFvance** [comment]
So – you installed the latest version? I don’t need to do that.

Thank you,
Karen
