### ISSUE TITLE
Product List - Vendor column is displaying incorrectly

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#23]
The labels inside the product list are still misaligned - see this screenshot.

https://cloud.githubusercontent.com/assets/12396651/7948333/1ce8d232-0951-11e5-9098-b6049560708c.JPG

**Comment by joelworsham** [comment]
This is not something that this plugin causes. I can't say what is causing it though. Sorry about that!

**Comment by joelworsham** [comment]
Actually, my apologies, it may be. Let me look into it.

**Comment by TDFvance** [comment]
OK. Well I guess we’ll just move on.

**Comment by TDFvance** [comment]
Thank you! I just don’t want it to look like it’s broken.

**Comment by joelworsham** [comment]
Hmmm, shoot. It looks like there's a conflict with the plugin on the server. Could I get FTP access to manually delete / deactivate the plugin?

**Comment by joelworsham** [comment]
Nevermind, I found the FTP credentials.

**Comment by joelworsham** [comment]
All set
