### ISSUE TITLE
Plugin Configuration questions

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#4]
I have reviewed the Documentation surrounding the plugin and have the following questions:
1) How do I add vendors?
2) If they are added as users, how are they associated with their teams? I don't see a field for identifying a parent user.
3) Do we have different user classes for Level 1, Level 2 and Level 3 or are they all entered as "Vendors"? See question 5 - are some of these other names different?
4) Can I associate different products with different vendors? If so, I don't see anywhere on the Product pages that allows for that.
5) I believe I have too many different User Classes associated with selling (perhaps some residual from when we were testing other potential plugin solutions. Can you let us know which user classes we should have and should we remove any of these? I have: Vendor, Shop Manager, Seller, Pending Vendor, Master Vendor and Master Seller.

**Comment by joelworsham** [comment]
1) Add a user, just like normal, and then give them the "Vendor" role.
2) Once the user is identified as a vendor, more settings become available (vendor parent, vendor name, vendor email, etc)
3) Yes, the "level" is determined by the ancestor depth.
4) No, all vendors have the same products. It was determined that this was the desired functionality. In the current scope, this is not possible, but it's always possible to expand the scope and include that.
5) A lot of those are created by WooCommerce. The user role you want is simply "Vendor".
