### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#5]
I've reviewed the plugin so far. I have two small tweaks. However, I have not yet entered any distributors or conducted any testing. I just wanted to capture what I saw so far.

Two known modifications at this time:
1) Can we add a fourth volume tier - Platinum - with a 30% commission/discount?
2) On the Vendor Updates/Modifications page - there is a column for "Instigator" and one for "Victim"
Let's change those to read "Initiated By" and "User Being Modified."

**Comment by joelworsham** [comment]
1) sure thing!
2) Yes, that verbage was very raw and I was planning on figuring out something better for the final product. We can use that verbage.

**Comment by TDFvance** [comment]
Excellent. Thank you.
