### ISSUE TITLE
Creating Vendors as Users - Error

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#6]
![vendorparenterror](https://cloud.githubusercontent.com/assets/12396651/7571567/686f14c2-f7e6-11e4-9011-12e9bea33427.JPG)

Creating Vendors as Users.

**Comment by joelworsham** [comment]
I've updated the plugin in attempt to fix this issue, although I could not replicate the issue for myself.

Please try the following:
1. Delete the plugin from your website
2. Download the new version of the plugin
3. Install the plugin
4. See if that error persists

**Comment by TDFvance** [comment]
I’m sorry I’m not as familiar with GitHub. Where in the interface do I download the new version of the plugin?

**Comment by TDFvance** [comment]
I think I found it, but how do I know for certain it’s the new version? Is the only downloadable version always the newest version?

**Comment by joelworsham** [comment]
Yes, the only downloadable version is the most recent version. To get it, you click "Download Zip" from [here](https://github.com/realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS)

**Comment by TDFvance** [comment]
This is now working. I'm sending other issues as I spot them.

**Comment by joelworsham** [comment]
Great! Glad to hear it
