### ISSUE TITLE
Vendor Updates Chart?

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#7]
![vendorupdates](https://cloud.githubusercontent.com/assets/12396651/7571737/97ac409c-f7e7-11e4-913c-adb263b9f4c3.JPG)

We should probably add a column for the User Name affected by the change? Unless the "Victim" column should be reading that. It isn't currently - I'm just getting N/As.

**Comment by joelworsham** [comment]
I will look into this. You should be getting the user name.
