### ISSUE TITLE
Store Displaying?

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#8]
I'm assuming I can't get the Vendor stores to come up because I haven't been able to set the vendor slugs?

![displayingstore](https://cloud.githubusercontent.com/assets/12396651/7572141/2218a6ce-f7ea-11e4-9822-aa1d5cbe6a96.JPG)

**Comment by joelworsham** [comment]
The slug should be automatically created based on the vendor name. Could you tell me the name of the vendor you're trying to view and the URL you're using?

**Comment by joelworsham** [comment]
And also, are you currently logged in as an administrator of the site?

**Comment by TDFvance** [comment]
I’ve tried:

/shop/kathie-russell
/shop/kathier
/shop/kathie-r

I’m not sure about the slug situation. The documentation said to start with /shop/.

Thanks,
Karen

**Comment by TDFvance** [comment]
I was logged in as an administrator when I added users.

**Comment by joelworsham** [comment]
What is the "Vendor Name"?

**Comment by TDFvance** [comment]
I do not have access to “Vendor Name” as a field because that section of the User profile is giving me an error. I’m not able to set anything associated with the plugin until this error is resolved.

Thoughts?

I need this resolved as soon as possible. I have a meeting with the client this afternoon and had hoped to show them at least some of this back-end functionality.

Please advise when you think we’ll be able to solve this error.

**Comment by joelworsham** [comment]
It's possible this issue is caused by something with #6. Please follow the steps in #6 and confirm that issue is resolved, and then see if this is still an issue.

**Comment by TDFvance** [comment]
This is now working.

**Comment by joelworsham** [comment]
Great
