### ISSUE TITLE
Discounts

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#9]
There are two scenarios where the Volume Commission Tier is in place, correct?

1) When a customer of mine goes to my selling page, they see the product at full-price, but the commission calculated for me is the 30%.

2) When I login as a Vendor, I receive my orders at a discounted rate?

For example, a Platinum-level person logs in and puts items in the cart as a customer to buy product. The price should reflect a 30% discount for me shopping (this is Volume Tier #1) Gold is #2, Silver is #3, and Bronze is #4.

I'm not seeing the discount reflected in the cart.

Am I missing the place where I set the commission/discount for each tier?

**Comment by joelworsham** [comment]
We had decided to forgo the discounts for now, as the commission being calculated at the end of the month means it still comes out in the wash.

We could include this instead of calculating in the commission from when a vendor buys from himself, but that is outside of the scope of the original project

**Comment by TDFvance** [comment]
How much time would it be to add the discount if the vendor buys from himself? Any ideas on the number of hours?

**Comment by joelworsham** [comment]
I'd say about 2 hrs.

**Comment by TDFvance** [comment]
Can I get a total hour count on the project to date? Then I’ll be able to look at the budget situation and let you know if I can green-light that.

**Comment by joelworsham** [comment]
Original estimate was 20. So with the discounts, 22.

**Comment by TDFvance** [comment]
I met with the client yesterday, and the discount on the front end is critical for the agreements they've signed. So please go ahead and implement.

I'm opening a new issue with the other quality issues we've noticed that need to be dealt with.
